# Generated by Django 3.2.3 on 2021-06-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicar_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creador', models.CharField(max_length=50)),
                ('comentarios', models.TextField(max_length=500)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('correo', models.EmailField(max_length=250)),
            ],
            options={
                'verbose_name': 'Publicar_Post',
                'verbose_name_plural': 'Publicar_Posts',
                'ordering': ['id'],
            },
        ),
    ]
