# Generated by Django 3.2.3 on 2021-06-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_content',
            field=models.TextField(default='vacio', max_length=100),
            preserve_default=False,
        ),
    ]
