# Generated by Django 3.2.3 on 2021-06-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
