# Generated by Django 3.2.3 on 2021-06-09 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210609_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='date_post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text_content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='state',
        ),
    ]
