# Generated by Django 3.2.3 on 2021-06-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_content',
            field=models.TextField(),
        ),
    ]
